services:
  - type: web
    name: emert-crm
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /api/analytics/dashboard

